# Generated by Django 3.2 on 2021-05-07 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('img1', models.ImageField(blank=True, upload_to='products')),
                ('title', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('size', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=555)),
                ('weigth', models.CharField(max_length=20)),
                ('dimensions', models.CharField(max_length=50)),
                ('materials', models.CharField(max_length=200)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.category')),
                ('saller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
