# Generated by Django 3.1.7 on 2021-05-24 14:43

import app_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0005_auto_20210508_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.ImageField(blank=True, upload_to=app_products.models.img_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(blank=True, upload_to=app_products.models.img_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.ImageField(blank=True, upload_to=app_products.models.img_path),
        ),
    ]
