# Generated by Django 3.2 on 2021-05-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gendar',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
